export default function iwasheredata(){
    const data = [
        { "province": "Abra" },
        { "province": "Agusan del Norte"},
        { "province": "Agusan del Sur"},
        { "province": "Aklan"},
        { "province": "Albay"},
        { "province": "Antique"},
        { "province": "Apayao"},
        { "province": "Aurora"},
        { "province": "Basilan"},
        { "province": "Bataan"},
        { "province": "Batanes"},
        { "province": "Batangas"},
        { "province": "Benguet"},
        { "province": "Biliran"},
        { "province": "Bohol"},
        { "province": "Bukidnon"},
        { "province": "Bulacan"},
        { "province": "NCR, City of Manila, First District"},
        { "province": "Cagayan"},
        { "province": "Camarines Norte"},
        { "province": "Camarines Sur"},
        { "province": "Camiguin"},
        { "province": "Capiz"},
        { "province": "Catanduanes"},
        { "province": "Cavite"},
        { "province": "Cebu"},
        { "province": "Compostela Valley"},
        { "province": "Davao del Norte"},
        { "province": "Davao del Sur" },
        { "province": "Davao Occidental"},
        { "province": "Davao Oriental"},
        { "province": "Dinagat Islands"},
        { "province": "Eastern Samar"},
        { "province": "Guimaras"},
        { "province": "Ifugao"},
        { "province": "Ilocos Norte"},
        { "province": "Ilocos Sur"},
        { "province": "Iloilo"},
        { "province": "City of Isabela"},
        { "province": "Isabela"},
        { "province": "Kalinga"},
        { "province": "La Union"},
        { "province": "Laguna"},
        { "province": "Lanao del Norte"},
        { "province": "Lanao del Sur"},
        { "province": "Leyte"},
        { "province": "Maguindanao"},
        { "province": "Marinduque"},
        { "province": "Masbate"},
        { "province": "Misamis Occidental"},
        { "province": "Misamis Oriental"},
        { "province": "Mountain Province"},
        { "province": "NCR, Fourth District"},
        { "province": "NCR, Third District"},
        { "province": "NCR, Second District"},
        { "province": "Negros Occidental"},
        { "province": "Negros Oriental"},
        { "province": "Northern Samar"},
        { "province": "Nueva Ecija"},
        { "province": "Nueva Vizcaya"},
        { "province": "Occidental Mindoro"},
        { "province": "Oriental Mindoro"},
        { "province": "Palawan"},
        { "province": "Pampanga"},
        { "province": "Pangasinan"},
        { "province": "Quezon"},
        { "province": "Quirino"},
        { "province": "Rizal"},
        { "province": "Romblon"},
        { "province": "Samar"},
        { "province": "Sarangani"},
        { "province": "Siquijor"},
        { "province": "Sorsogon"},
        { "province": "Cotabato"},
        { "province": "Cotabato City"},
        { "province": "South Cotabato"},
        { "province": "Southern Leyte"},
        { "province": "Sultan Kudarat"},
        { "province": "Sulu"},
        { "province": "Surigao del Norte"},
        { "province": "Surigao del Sur"},
        { "province": "Tarlac"},
        { "province": "Tawi-Tawi"},
        { "province": "Zambales"},
        { "province": "Zamboanga del Norte"},
        { "province": "Zamboanga del Sur"},
        { "province": "Zamboanga Sibugay"}
    ]

    return data
    
}